### ISSUE TITLE
Jnius dependency on Cython

### ISSUE THREAD

**Issue by MidpriceDog** [MidpriceDog/the-odds-api-client#2]
Package install from requirements.txt is successful until install of the  'jnius==1.1.0` package. Error message asserts that installation depends on Cython. Cython is downloaded as shown in the output below but seems like it is not yet installed leading to this dependency error. 

```
(oddsapienv) (base) MacBook-Pro-84:the-odds-api-client Ian$ pip install -r requirements.txt
Collecting attr==0.3.2
  Downloading attr-0.3.2-py2.py3-none-any.whl (3.3 kB)
Collecting attrs==22.1.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting brotli==1.0.9
  Downloading Brotli-1.0.9-cp310-cp310-macosx_10_9_x86_64.whl (421 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 421.8/421.8 kB 322.5 kB/s eta 0:00:00
Collecting brotlicffi==1.0.9.2
  Downloading brotlicffi-1.0.9.2-cp35-abi3-macosx_10_9_x86_64.whl (427 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.2/427.2 kB 233.3 kB/s eta 0:00:00
Collecting ConfigParser==5.3.0
  Downloading configparser-5.3.0-py3-none-any.whl (19 kB)
Collecting cryptography==39.0.1
  Downloading cryptography-39.0.1-cp36-abi3-macosx_10_12_x86_64.whl (2.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 511.7 kB/s eta 0:00:00
Collecting Cython==0.29.33
  Downloading Cython-0.29.33-py2.py3-none-any.whl (987 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 987.3/987.3 kB 443.3 kB/s eta 0:00:00
Collecting diff==0.6.1
  Downloading diff-0.6.1-py2.py3-none-any.whl (5.1 kB)
Collecting dl==0.1.0
  Downloading dl-0.1.0.tar.gz (5.2 kB)
  Preparing metadata (setup.py) ... done
Collecting docutils==0.17.1
  Using cached docutils-0.17.1-py2.py3-none-any.whl (575 kB)
Collecting flake8==6.0.0
  Downloading flake8-6.0.0-py2.py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 kB 271.8 kB/s eta 0:00:00
Collecting HTMLParser==0.0.2
  Downloading HTMLParser-0.0.2.tar.gz (6.0 kB)
  Preparing metadata (setup.py) ... done
Collecting ipython==8.10.0
  Downloading ipython-8.10.0-py3-none-any.whl (784 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 784.3/784.3 kB 761.8 kB/s eta 0:00:00
Collecting ipywidgets==8.0.4
  Downloading ipywidgets-8.0.4-py3-none-any.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.8/137.8 kB 977.2 kB/s eta 0:00:00
Collecting Jinja2==3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting jnius==1.1.0
  Downloading jnius-1.1.0.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/22/t02q5_5x0g3d9dqnyvzj_6h40000gn/T/pip-install-_hpguf7_/jnius_e9b66d1a46a74c0d95029d05a6d46bee/setup.py", line 53, in <module>
          from Cython.Distutils import build_ext
      ModuleNotFoundError: No module named 'Cython'
      
      
      You need Cython to compile Pyjnius.
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: pip install --upgrade `pip`
```

If anyone knows if this reasoning (regarding Cython being downloaded but not yet installed), please do respond.

**Comment by MidpriceDog** [comment]
Temporary solution is to instead run
Temporary solution (but not a good one) is to run
```
pip install Cython
pip install -r requirements.txt
```

**Comment by MidpriceDog** [comment]
A number of packages including jnius were generated as dependencies when running `pip-reqs` in a virtual environment I believed to be clean that in reality turned out to not be required. I removed the problematic ones from the dependencies list in `pyproject.toml` and `requirements.txt` in the latest commit to the main branch.
